GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Testing 123",
    "author": "Joe Smith",
    "url": "www.foo.com",
    "likes": 5
}
 
###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/persons/60147782287aa506d081ff3f